/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class runOpticalFlow */

#ifndef _Included_runVO
#define _Included_runVO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     runVO
 * Method:    VO
 * Signature: (Ljava/nio/ByteBuffer;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_runVO_VO
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
