/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class runOpticalFlow */

#ifndef _Included_runOpticalFlow
#define _Included_runOpticalFlow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     runOpticalFlow
 * Method:    opticalFlow
 * Signature: (Ljava/nio/ByteBuffer;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_runOpticalFlow_opticalFlow
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
